name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  php_lib:
    name: CI
    uses: GabrielSoares-Dev/workflows/.github/workflows/php-lib-CI.yml@master
    with:
      php_version: '7.4'